export const SHOW_EDIT_POPUP_TRUCK = 'SHOW_EDIT_POPUP_TRUCK';
export const HIDDEN_EDIT_POPUP_TRUCK = 'HIDDEN_EDIT_POPUP_TRUCK';
export const GET_LIST_TRUCKS = 'GET_LIST_TRUCKS';
export const EDIT_TRUCK = 'EDIT_TRUCK';
export const DELETE_TRUCK = 'DELETE_TRUCK';
export const HIDDEN_DELETE_POPUP_TRUCK = 'HIDDEN_DELETE_POPUP_TRUCK';
export const SHOW_DELETE_POPUP_TRUCK = 'SHOW_DELETE_POPUP_TRUCK';
export const CREATE_TRUCK = 'CREATE_TRUCK';
export const SET_ID_SELECTED_TRUCK = 'SET_ID_SELECTED_TRUCK';
export const UPDATE_LIST_TRUCKS_FILTER = 'UPDATE_LIST_TRUCKS_FILTER';
export const LOGIN_USER = 'LOGIN_USER';

//tabla de camiones 